-- Create audit_logs table (master table for all audit entries)
CREATE TABLE IF NOT EXISTS `audit_logs` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `entity_type` varchar(50) NOT NULL COMMENT 'Type of entity: invoice, buyer, product, user',
  `entity_id` int(11) NOT NULL COMMENT 'ID of the affected entity',
  `operation` enum('CREATE','UPDATE','DELETE') NOT NULL COMMENT 'Type of operation performed',
  `user_id` int(11) DEFAULT NULL COMMENT 'ID of user who performed the operation',
  `user_email` varchar(255) DEFAULT NULL COMMENT 'Email of user who performed the operation',
  `user_name` varchar(255) DEFAULT NULL COMMENT 'Full name of user who performed the operation',
  `user_role` varchar(50) DEFAULT NULL COMMENT 'Role of user who performed the operation',
  `tenant_id` int(11) DEFAULT NULL COMMENT 'Tenant/Company ID where operation was performed',
  `tenant_name` varchar(255) DEFAULT NULL COMMENT 'Tenant/Company name',
  `old_values` JSON DEFAULT NULL COMMENT 'Previous values before update/delete (JSON format)',
  `new_values` JSON DEFAULT NULL COMMENT 'New values after create/update (JSON format)',
  `changed_fields` JSON DEFAULT NULL COMMENT 'List of fields that were changed (for updates)',
  `ip_address` varchar(45) DEFAULT NULL COMMENT 'IP address of the user',
  `user_agent` text DEFAULT NULL COMMENT 'User agent string from the request',
  `request_id` varchar(100) DEFAULT NULL COMMENT 'Unique request identifier for tracking',
  `additional_info` JSON DEFAULT NULL COMMENT 'Additional context information',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_audit_entity` (`entity_type`, `entity_id`),
  KEY `idx_audit_user` (`user_id`),
  KEY `idx_audit_operation` (`operation`),
  KEY `idx_audit_tenant` (`tenant_id`),
  KEY `idx_audit_created_at` (`created_at`),
  KEY `idx_audit_user_email` (`user_email`),
  KEY `idx_audit_entity_operation` (`entity_type`, `operation`),
  CONSTRAINT `fk_audit_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_audit_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
