-- Create audit_summary table for quick admin overview
CREATE TABLE IF NOT EXISTS `audit_summary` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `entity_type` varchar(50) NOT NULL,
  `entity_id` int(11) NOT NULL,
  `entity_name` varchar(255) DEFAULT NULL COMMENT 'Human-readable name of the entity',
  `total_operations` int(11) DEFAULT 0 COMMENT 'Total number of operations on this entity',
  `created_by_user_id` int(11) DEFAULT NULL,
  `created_by_email` varchar(255) DEFAULT NULL,
  `created_by_name` varchar(255) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `last_modified_by_user_id` int(11) DEFAULT NULL,
  `last_modified_by_email` varchar(255) DEFAULT NULL,
  `last_modified_by_name` varchar(255) DEFAULT NULL,
  `last_modified_at` timestamp NULL DEFAULT NULL,
  `tenant_id` int(11) DEFAULT NULL,
  `tenant_name` varchar(255) DEFAULT NULL,
  `is_deleted` tinyint(1) DEFAULT 0 COMMENT 'Whether the entity has been deleted',
  `deleted_by_user_id` int(11) DEFAULT NULL,
  `deleted_by_email` varchar(255) DEFAULT NULL,
  `deleted_by_name` varchar(255) DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_entity` (`entity_type`, `entity_id`),
  KEY `idx_summary_entity_type` (`entity_type`),
  KEY `idx_summary_tenant` (`tenant_id`),
  KEY `idx_summary_created_by` (`created_by_user_id`),
  KEY `idx_summary_last_modified` (`last_modified_by_user_id`),
  KEY `idx_summary_deleted` (`is_deleted`),
  CONSTRAINT `fk_summary_created_by` FOREIGN KEY (`created_by_user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_summary_last_modified_by` FOREIGN KEY (`last_modified_by_user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_summary_deleted_by` FOREIGN KEY (`deleted_by_user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_summary_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
